workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - app_store_credentials
      vars:
        FLUTTER_VERSION: 3.24.5
    scripts:
      - name: Set up key properties
        script: |
          echo "No keystore needed for this build"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - daviddiaz-bot@users.noreply.github.com
